### ISSUE TITLE
Exim+TLS Received headers

### ISSUE THREAD

**Issue by Takika** [oszto90/Roundcube_TLS_Icon_with_Hmailserver#3]
I have Exim mailserver with TLS support. My last Received header looks like this:
```
Received: from [209.85.167.171] (helo=mail-oi1-f171.google.com)
    by alkoholista.hu with esmtps (TLS1.3) tls TLS_AES_128_GCM_SHA256
    (Exim 4.95 (FreeBSD))
    (envelope-from <taki0501@gmail.com>)
    id 1pCeLD-000AfX-M4
    for taki@alkoholista.hu;
    Tue, 03 Jan 2023 11:16:33 +0100
```

I think that Exim has different format of Received headers than your mailserver, so the plugin can't recognize the TLS connection.
Can you modify your plugin to detect these lines too?

**Comment by oszto90** [comment]
Hello,

I can't test it because I don't have an Exim server, but I recommend that you make the following changes:
In the `tls_icon_with_hmail.php` file, please replace this line:
`$needle = "(version=";`
For this:
`$needle = "(";`

AND
replace this line:
`if ( preg_match_all('/\(version=TLSv1.[2-3].*\)/im', $Received, $items, PREG_PATTERN_ORDER) ) {`
For this:
`if ( preg_match_all('/\(TLSv1.[2-3].*\)/im', $Received, $items, PREG_PATTERN_ORDER) ) {`

If this helped to solve the problem, please let me know and then I will create another version that will work for Exim with this modification.

**Comment by oszto90** [comment]
Since this error is not really related to the current plugin because it was made for hmailserver. (also in his name) So it's not relevant.

**Comment by Takika** [comment]
Ok, I try to make a fork with configurable header lines.
